-- Definición de la tabla: products
CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  sku TEXT,
  name TEXT,
  brand TEXT,
  shoeClass TEXT,
  category TEXT,
  shoeType TEXT,
  price INTEGER,
  costPrice INTEGER,
  image TEXT,
  description TEXT,
  isFeatured BOOLEAN,
  sizes ARRAY,
  totalStock INTEGER
);

-- Datos iniciales para products
INSERT INTO products (id, sku, name, brand, shoeClass, category, shoeType, price, costPrice, image, description, isFeatured, sizes, totalStock) VALUES ('prod-1', 'ZAP-DEP-001', 'Air Velocity Pro Runner', 'Nike', 'Caballeros', 'Deportivos', 'Running / Trainers', 2499, 1300, 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=800', 'Tenis de alto rendimiento con cápsula de aire continua y mallas ultratranspirables.', true, '{ size: ''39'', stock: 4 },{ size: ''40'', stock: 6 },{ size: ''41'', stock: 8 },{ size: ''42'', stock: 5 },{ size: ''43'', stock: 2 },{ size: ''44'', stock: 1 }', 26);
INSERT INTO products (id, sku, name, brand, shoeClass, category, shoeType, price, costPrice, image, description, isFeatured, sizes, totalStock) VALUES ('prod-2', 'ZAP-FOR-002', 'Oxford Milano Royale', 'Gucci', 'Caballeros', 'Formales', 'Oxford / Derby', 3899, 1950, 'https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&w=800', 'Zapatos de vestir Oxford hechos a mano en piel de ternera italiana con costura fina Goodyear.', true, '{ size: ''39'', stock: 3 },{ size: ''40'', stock: 4 },{ size: ''41'', stock: 6 },{ size: ''42'', stock: 3 },{ size: ''43'', stock: 1 }', 17);
INSERT INTO products (id, sku, name, brand, shoeClass, category, shoeType, price, costPrice, image, description, isFeatured, sizes, totalStock) VALUES ('prod-3', 'ZAP-BOT-003', 'Chelsea Boot Heritage Nobuk', 'Timberland', 'Caballeros', 'Botas', 'Chelsea / Ankle Boot', 3299, 1600, 'https://images.pexels.com/photos/1159670/pexels-photo-1159670.jpeg?auto=compress&cs=tinysrgb&w=800', 'Botines estilo Chelsea impermeables en cuero Nobuk con panal elástico reforzado.', false, '{ size: ''38'', stock: 2 },{ size: ''39'', stock: 1 },{ size: ''40'', stock: 5 },{ size: ''41'', stock: 4 },{ size: ''42'', stock: 3 },{ size: ''43'', stock: 2 }', 17);
INSERT INTO products (id, sku, name, brand, shoeClass, category, shoeType, price, costPrice, image, description, isFeatured, sizes, totalStock) VALUES ('prod-4', 'ZAP-TAC-004', 'Stiletto Velvet Glamour 10cm', 'Jimmy Choo', 'Damas', 'Tacones y Plataformas', 'Stiletto / Taco Aguja', 4150, 2000, 'https://images.pexels.com/photos/137603/pexels-photo-137603.jpeg?auto=compress&cs=tinysrgb&w=800', 'Zapatilla estilizada con taco de aguja de 10cm en gamuza fina con forro textil satinado.', true, '{ size: ''35'', stock: 2 },{ size: ''36'', stock: 4 },{ size: ''37'', stock: 5 },{ size: ''38'', stock: 3 },{ size: ''39'', stock: 1 }', 15);
INSERT INTO products (id, sku, name, brand, shoeClass, category, shoeType, price, costPrice, image, description, isFeatured, sizes, totalStock) VALUES ('prod-5', 'ZAP-CAS-005', 'Urban Suede Penny Loafer', 'Puma', 'Unisex', 'Casual y Mocasines', 'Loafer / Mocasín', 1899, 950, 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=800', 'Mocasín de vestir sin agujetas en ante suave con plantilla de espuma anatómica.', false, '{ size: ''37'', stock: 3 },{ size: ''38'', stock: 4 },{ size: ''39'', stock: 5 },{ size: ''40'', stock: 7 },{ size: ''41'', stock: 8 },{ size: ''42'', stock: 4 }', 31);
INSERT INTO products (id, sku, name, brand, shoeClass, category, shoeType, price, costPrice, image, description, isFeatured, sizes, totalStock) VALUES ('prod-6', 'ZAP-SAN-006', 'Verano Gold Gladiator Strap', 'Michael Kors', 'Damas', 'Sandalias y Pantuflas', 'Sandalia Plana / Gladiator', 1650, 800, 'https://images.pexels.com/photos/3389419/pexels-photo-3389419.jpeg?auto=compress&cs=tinysrgb&w=800', 'Sandalia de tiras metálicas doradas con hebilla ajustable al tobillo y suela antideslizante.', false, '{ size: ''35'', stock: 2 },{ size: ''36'', stock: 3 },{ size: ''37'', stock: 6 },{ size: ''38'', stock: 4 },{ size: ''39'', stock: 2 }', 17);
INSERT INTO products (id, sku, name, brand, shoeClass, category, shoeType, price, costPrice, image, description, isFeatured, sizes, totalStock) VALUES ('prod-7', 'ZAP-IND-007', 'Titan Safety Steel Toe Boot', 'Caterpillar', 'Caballeros', 'Trabajo e Industrial', 'Bota Industrial / Trabajo', 3499, 1750, 'https://images.pexels.com/photos/267320/pexels-photo-267320.jpeg?auto=compress&cs=tinysrgb&w=800', 'Bota industrial con casquillo de acero dieléctrico y suela antideslizante resistente a aceites.', true, '{ size: ''40'', stock: 4 },{ size: ''41'', stock: 6 },{ size: ''42'', stock: 5 },{ size: ''43'', stock: 3 },{ size: ''44'', stock: 2 }', 20);
INSERT INTO products (id, sku, name, brand, shoeClass, category, shoeType, price, costPrice, image, description, isFeatured, sizes, totalStock) VALUES ('prod-8', 'ZAP-ESC-008', 'Escolar Flexi Comfort Black', 'Flexi', 'Niños', 'Escolar', 'Choclo / Zapato Escolar', 1199, 580, 'https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&w=800', 'Zapato escolar resistente en piel natural con ajuste por velcro y plantilla ergonómica.', false, '{ size: ''32'', stock: 5 },{ size: ''33'', stock: 6 },{ size: ''34'', stock: 8 },{ size: ''35'', stock: 4 },{ size: ''36'', stock: 3 }', 26);
INSERT INTO products (id, sku, name, brand, shoeClass, category, shoeType, price, costPrice, image, description, isFeatured, sizes, totalStock) VALUES ('prod-9', 'ZAP-DEP-009', 'Ultraboost Marathon Primeknit', 'Adidas', 'Unisex', 'Deportivos', 'Running / Trainers', 2899, 1450, 'https://images.pexels.com/photos/1478442/pexels-photo-1478442.jpeg?auto=compress&cs=tinysrgb&w=800', 'Tenis deportivos con tecnología de retorno de energía Boost y suela Continental.', true, '{ size: ''37'', stock: 3 },{ size: ''38'', stock: 4 },{ size: ''39'', stock: 5 },{ size: ''40'', stock: 6 },{ size: ''41'', stock: 4 },{ size: ''42'', stock: 2 }', 24);
INSERT INTO products (id, sku, name, brand, shoeClass, category, shoeType, price, costPrice, image, description, isFeatured, sizes, totalStock) VALUES ('prod-10', 'ZAP-CAS-010', 'Street Star Canvas Sneaker', 'Converse', 'Niñas', 'Casual y Mocasines', 'Sneaker Urbano', 1399, 690, 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=800', 'Sneakers de lona juvenil con diseño retro, ojetes de aluminio y puntera de caucho.', false, '{ size: ''33'', stock: 4 },{ size: ''34'', stock: 5 },{ size: ''35'', stock: 6 },{ size: ''36'', stock: 3 }', 18);
